site_name: texsquisite
site_description: A LaTex linter written in Python.
site_author: Philip Mocz
repo_url: https://github.com/pmocz/texsquisite

# Set the site URL by using a Read the Docs environment variable:
# https://docs.readthedocs.io/en/stable/reference/environment-variables.html
site_url: !ENV READTHEDOCS_CANONICAL_URL

theme:
  name: material
